spring:
  application:
    name: GoodLearnAI
  datasource:
    url: jdbc:mysql://10.180.44.134:3306/good_learn_ai_NEW?useSSL=false&serverTimezone=UTC
    username: root
    password: zzx
    driver-class-name: com.mysql.cj.jdbc.Driver
  devtools:
    restart:
      enabled: true
      # 自定义监控的路径，这里只监控 src/main/java 目录
      additional-paths: src/main/java
      # 排除不必要的路径，防止静态资源文件等变化触发重启
      exclude: static/**,public/**,templates/**,log/**
  ai:
    openai:
      api-key: sk-058644562a714d92b48c41136ca54a74
      base-url: https://api.deepseek.com
      chat:
        options:
          model: deepseek-chat
    mcp:
      client:
        stdio:
          servers-configuration: ./classpath:mcp-servers.json
  mvc:
    servlet:
      path: /api
  data:
    redis:
      host: 10.180.44.134
      port: 6379
      timeout: 5000
      password: zxcvg123

server:
  port: 8080



mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:mapper/*.xml


jwt:
  secret: mouse-mouse
  expirationMs: 86400000

logging:
  level:
    root: info
    com.example.goodlearnai: debug